// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: techdecaf/k2s/v1/deployment.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeploymentType int32

const (
	DeploymentType_DEPLOYMENT_TYPE_UNSPECIFIED DeploymentType = 0
	DeploymentType_DEPLOYMENT_TYPE_API         DeploymentType = 1
	DeploymentType_DEPLOYMENT_TYPE_SERVICE     DeploymentType = 2
)

// Enum value maps for DeploymentType.
var (
	DeploymentType_name = map[int32]string{
		0: "DEPLOYMENT_TYPE_UNSPECIFIED",
		1: "DEPLOYMENT_TYPE_API",
		2: "DEPLOYMENT_TYPE_SERVICE",
	}
	DeploymentType_value = map[string]int32{
		"DEPLOYMENT_TYPE_UNSPECIFIED": 0,
		"DEPLOYMENT_TYPE_API":         1,
		"DEPLOYMENT_TYPE_SERVICE":     2,
	}
)

func (x DeploymentType) Enum() *DeploymentType {
	p := new(DeploymentType)
	*p = x
	return p
}

func (x DeploymentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeploymentType) Descriptor() protoreflect.EnumDescriptor {
	return file_techdecaf_k2s_v1_deployment_proto_enumTypes[0].Descriptor()
}

func (DeploymentType) Type() protoreflect.EnumType {
	return &file_techdecaf_k2s_v1_deployment_proto_enumTypes[0]
}

func (x DeploymentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeploymentType.Descriptor instead.
func (DeploymentType) EnumDescriptor() ([]byte, []int) {
	return file_techdecaf_k2s_v1_deployment_proto_rawDescGZIP(), []int{0}
}

type Deployment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata    *DeploymentMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Environment map[string]string   `protobuf:"bytes,3,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_techdecaf_k2s_v1_deployment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_techdecaf_k2s_v1_deployment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_techdecaf_k2s_v1_deployment_proto_rawDescGZIP(), []int{0}
}

func (x *Deployment) GetMetadata() *DeploymentMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Deployment) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

type DeploymentMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type    DeploymentType `protobuf:"varint,2,opt,name=type,proto3,enum=techdecaf.k2s.v1.DeploymentType" json:"type,omitempty"`
	Name    string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Version string         `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *DeploymentMetadata) Reset() {
	*x = DeploymentMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_techdecaf_k2s_v1_deployment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeploymentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentMetadata) ProtoMessage() {}

func (x *DeploymentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_techdecaf_k2s_v1_deployment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentMetadata.ProtoReflect.Descriptor instead.
func (*DeploymentMetadata) Descriptor() ([]byte, []int) {
	return file_techdecaf_k2s_v1_deployment_proto_rawDescGZIP(), []int{1}
}

func (x *DeploymentMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeploymentMetadata) GetType() DeploymentType {
	if x != nil {
		return x.Type
	}
	return DeploymentType_DEPLOYMENT_TYPE_UNSPECIFIED
}

func (x *DeploymentMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeploymentMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_techdecaf_k2s_v1_deployment_proto protoreflect.FileDescriptor

var file_techdecaf_k2s_v1_deployment_proto_rawDesc = []byte{
	0x0a, 0x21, 0x74, 0x65, 0x63, 0x68, 0x64, 0x65, 0x63, 0x61, 0x66, 0x2f, 0x6b, 0x32, 0x73, 0x2f,
	0x76, 0x31, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x10, 0x74, 0x65, 0x63, 0x68, 0x64, 0x65, 0x63, 0x61, 0x66, 0x2e, 0x6b,
	0x32, 0x73, 0x2e, 0x76, 0x31, 0x22, 0xdf, 0x01, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x40, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x64, 0x65, 0x63,
	0x61, 0x66, 0x2e, 0x6b, 0x32, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x4f, 0x0a, 0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f,
	0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x74, 0x65,
	0x63, 0x68, 0x64, 0x65, 0x63, 0x61, 0x66, 0x2e, 0x6b, 0x32, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f,
	0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x65, 0x6e, 0x76, 0x69,
	0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x3e, 0x0a, 0x10, 0x45, 0x6e, 0x76, 0x69, 0x72,
	0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x88, 0x01, 0x0a, 0x12, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x34,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x74,
	0x65, 0x63, 0x68, 0x64, 0x65, 0x63, 0x61, 0x66, 0x2e, 0x6b, 0x32, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x2a, 0x67, 0x0a, 0x0e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x1b, 0x44, 0x45, 0x50, 0x4c, 0x4f, 0x59, 0x4d, 0x45,
	0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x44, 0x45, 0x50, 0x4c, 0x4f, 0x59, 0x4d,
	0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x50, 0x49, 0x10, 0x01, 0x12, 0x1b,
	0x0a, 0x17, 0x44, 0x45, 0x50, 0x4c, 0x4f, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x10, 0x02, 0x42, 0x09, 0x5a, 0x07, 0x70,
	0x6b, 0x67, 0x2f, 0x64, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_techdecaf_k2s_v1_deployment_proto_rawDescOnce sync.Once
	file_techdecaf_k2s_v1_deployment_proto_rawDescData = file_techdecaf_k2s_v1_deployment_proto_rawDesc
)

func file_techdecaf_k2s_v1_deployment_proto_rawDescGZIP() []byte {
	file_techdecaf_k2s_v1_deployment_proto_rawDescOnce.Do(func() {
		file_techdecaf_k2s_v1_deployment_proto_rawDescData = protoimpl.X.CompressGZIP(file_techdecaf_k2s_v1_deployment_proto_rawDescData)
	})
	return file_techdecaf_k2s_v1_deployment_proto_rawDescData
}

var file_techdecaf_k2s_v1_deployment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_techdecaf_k2s_v1_deployment_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_techdecaf_k2s_v1_deployment_proto_goTypes = []interface{}{
	(DeploymentType)(0),        // 0: techdecaf.k2s.v1.DeploymentType
	(*Deployment)(nil),         // 1: techdecaf.k2s.v1.Deployment
	(*DeploymentMetadata)(nil), // 2: techdecaf.k2s.v1.DeploymentMetadata
	nil,                        // 3: techdecaf.k2s.v1.Deployment.EnvironmentEntry
}
var file_techdecaf_k2s_v1_deployment_proto_depIdxs = []int32{
	2, // 0: techdecaf.k2s.v1.Deployment.metadata:type_name -> techdecaf.k2s.v1.DeploymentMetadata
	3, // 1: techdecaf.k2s.v1.Deployment.environment:type_name -> techdecaf.k2s.v1.Deployment.EnvironmentEntry
	0, // 2: techdecaf.k2s.v1.DeploymentMetadata.type:type_name -> techdecaf.k2s.v1.DeploymentType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_techdecaf_k2s_v1_deployment_proto_init() }
func file_techdecaf_k2s_v1_deployment_proto_init() {
	if File_techdecaf_k2s_v1_deployment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_techdecaf_k2s_v1_deployment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deployment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_techdecaf_k2s_v1_deployment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeploymentMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_techdecaf_k2s_v1_deployment_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_techdecaf_k2s_v1_deployment_proto_goTypes,
		DependencyIndexes: file_techdecaf_k2s_v1_deployment_proto_depIdxs,
		EnumInfos:         file_techdecaf_k2s_v1_deployment_proto_enumTypes,
		MessageInfos:      file_techdecaf_k2s_v1_deployment_proto_msgTypes,
	}.Build()
	File_techdecaf_k2s_v1_deployment_proto = out.File
	file_techdecaf_k2s_v1_deployment_proto_rawDesc = nil
	file_techdecaf_k2s_v1_deployment_proto_goTypes = nil
	file_techdecaf_k2s_v1_deployment_proto_depIdxs = nil
}
