name: ci
on: [pull_request]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aquasecurity/trivy-action@master
        with: { scan-type: "fs", scan-ref: "." }
  test:
    runs-on: ubuntu-latest
    needs: [scan]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with: { go-version: 1.19, cache: true }
      - name: install_tasks
        run: sh -c "$(curl -fsSL https://raw.github.com/techdecaf/tasks/master/install.sh)"
      - name: coverage
        run: tasks run coverage
